<?php

use App\Menu;
use Illuminate\Database\Seeder;

class MenuTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Menu::create(['restaurant_id' => '1','name' => 'Can Pop','description' => 'Choose from a variety of Coke products. Available in 335 mL cans.','image' => 'uploads/menu/1/Coke_Can.webp','category_id' => 30,'price' => 1.39]);
        Menu::create(['restaurant_id' => '1','name' => 'Bottle Pop','description' => 'Choose from a variety of Coke products. Available in 500 mL bottles.','image' => 'uploads/menu/1/Coke_Bottle.png','category_id' => 30,'price' => 2.29]);
        Menu::create(['restaurant_id' => '1','name' => '8 Jalapeno Poppers','description' => 'These spicy, comfort-food classics are fried to order and stuffed with zesty cream-cheese filling. And, of course, very poppable. Comes in order of 8.','image' => 'uploads/menu/1/JPOP.webp','category_id' => 29,'price' => 5.99]);
        Menu::create(['restaurant_id' => '1','name' => '10 Deep Fried Pickles','description' => 'Yes, you read that right. Deep-fried pickles. This tangy, pub-grub classic is available alongside your fave pizza! Comes in order of 10.','image' => 'uploads/menu/1/DPICK.webp','category_id' => 29,'price' => 5.99]);
        Menu::create(['restaurant_id' => '1','name' => 'Small Box of Fries','description' => 'Feel like fries with that pizza? Not a problem. It\'s all about you!? Enjoy a box of hot, crispy fries cooked in trans-fat free oil.','image' => 'uploads/menu/1/Box-of-Fries.webp','category_id' => 11,'price' => 3.89]);
        Menu::create(['restaurant_id' => '1','name' => 'Buffalo Chicken','description' => 'All the Zing, without the wing - This tangy, spicy pie is made for Game Day. Kick off with buffalo blue cheese sauce, grilled chicken, red onions, fire-roasted red peppers and mozzarella cheese.','image' => 'uploads/menu/1/buffalo-chicken-pizza.webp','category_id' => 14,'price' => 13.29]);
        Menu::create(['restaurant_id' => '1','name' => 'Mediterranean Vegetarian','description' => 'Topped with kalamata olives, broccoli, sun-dried tomatoes, grilled zucchini, red onions, feta cheese and mozzarella cheese. A healthy alternative.','image' => 'uploads/menu/1/medveg.webp','category_id' => 14,'price' => 16.79]);
        Menu::create(['restaurant_id' => '1','name' => 'Gourmet Thin Pesto Amore','description' => 'Fall in love with pesto all over again with this 10" thin crust topped with spinach, red onions, fire roasted red peppers, goat cheese, mozzarella and pesto sauce.','image' => 'uploads/menu/1/SPAGT.webp','category_id' => 14,'price' => 7.29]);
        Menu::create(['restaurant_id' => '1','name' => 'Keto Crust Pizza','description' => 'Get your pizza fix with less carbs! Create your own by selecting any toppings of your choice. Made with certified Keto Uncrust. See About our Food page for nutritional info.','image' => 'uploads/menu/1/SKE.webp','category_id' => 14,'price' => 12.79]);
        Menu::create(['restaurant_id' => '1','name' => 'Chocolate Truffles','description' => 'Rich chocolate covered truffles filled with a decadent chocolate ganache. Box of 15 truffles.','image' => 'uploads/menu/1/TRUF.webp','category_id' => 5,'price' => 5.99]);

        Menu::create(['restaurant_id' => '2','name' => 'Pepperoni Lover\'s®','description' => 'Double pepperoni and extra pizza mozzarella.','image' => 'uploads/menu/2/gV9esuNv3Pf3Zw7juGZDes7BYncYVQ6oUVo9jZBq.png','category_id' => 14,'price' => 12.99]);
        Menu::create(['restaurant_id' => '2','name' => 'Meat Lover\'s®','description' => 'Pepperoni, Italian sausage, mild sausage, beef topping, ham, bacon crumble and pizza mozzarella.','image' => 'uploads/menu/2/ir8q3adjxX3tYH3e4MxkkmJ5PDEblr9L4HzIptQ1.png','category_id' => 14,'price' => 15.54]);
        Menu::create(['restaurant_id' => '2','name' => 'Canadian','description' => 'Pepperoni, bacon crumble, mushrooms and pizza mozzarella.','image' => 'uploads/menu/2/VbYJ7GltcXNsTV4T983vresoizQNGuTGblGJqvXB.png','category_id' => 14,'price' => 13.99]);
        Menu::create(['restaurant_id' => '2','name' => 'Bbq Chicken','description' => 'Ultimate BBQ sauce, smoked aged cheddar cheese, grilled chicken strips, red onion, and green peppers','image' => 'uploads/menu/2/gAgrju8zs055r8CN2kAzkPLjgiLB5WF09tRQO5M6.png','category_id' => 14,'price' => 13.99]);
        Menu::create(['restaurant_id' => '2','name' => 'Traditional Wings','description' => 'Classic plump and juicy chicken wings tossed in your choice of sauce.','image' => 'uploads/menu/2/I7rOPehJqUeqoHrxq79efR2A4v2KKq6DDIZWDhb7.png','category_id' => 9,'price' => 10.50]);
        Menu::create(['restaurant_id' => '2','name' => 'Boneless Bites','description' => 'Crispy, breaded, 100% white meat chicken breast pieces tossed in your choice of sauce.','image' => 'uploads/menu/2/k3K0Ah8j78Mss1ZGiK7p79fjDvNdoa90jB17ggyG.png','category_id' => 9,'price' => 11.29]);
        Menu::create(['restaurant_id' => '2','name' => 'Chicken Caesar Salad','description' => 'Add even more flavour to your Caesar salad by topping it with tender grilled seasoned chicken breast','image' => 'uploads/menu/2/OFcDdlNvZckVJk4A7VNtFzW1fJhRfkXyNQoK7Yw8.png','category_id' => 10,'price' => 15.99]);
        Menu::create(['restaurant_id' => '2','name' => 'Pepsi 2 Litre Bottle','description' => 'The bold, robust, effervescently magic cola.','image' => 'uploads/menu/2/41e7b17d-84c6-4812-b685-a1e3029a35c5.jpg','category_id' => 30,'price' => 3.49]);
        Menu::create(['restaurant_id' => '2','name' => 'The Ultimate Hershey\'s Chipits Cookie','description' => 'Freshly baked. Served warm and gooey. Try it today!','image' => 'uploads/menu/2/99e8bbfd-fb49-412b-a9f7-5ac60183fa5f.jpg','category_id' => 5,'price' => 6.99]);
        Menu::create(['restaurant_id' => '2','name' => 'Creamy Chicken Alfredo','description' => 'Sliced grilled chicken breast tossed with oven-baked rotini in a creamy alfredo sauce. Includes fresh breadsticks.','image' => 'uploads/menu/2/6050d919-cef9-4c61-bb97-bd8468094ffc.jpg','category_id' => 17,'price' => 16.99]);

        Menu::create(['restaurant_id' => '3','name' => '8 PIECE BUCKET','description' => '8 pieces of our Canadian farm raised and hand-breaded Secret Recipe chicken.','image' => 'uploads/menu/3/ww4A1m7z4DN2eLpARCuyEowFzEHTfI4GyAeRorUY.jpeg','category_id' => 9,'price' => 12.99]);
        Menu::create(['restaurant_id' => '3','name' => '12 PIECE BUCKET','description' => '12 pieces of our Canadian farm raised and hand-breaded Secret Recipe chicken.','image' => 'uploads/menu/3/Vuzm26jNqFxh1lDwKbwj1abGpqJAlHcf0MsdyjLB.jpeg','category_id' => 9,'price' => 15.99]);
        Menu::create(['restaurant_id' => '3','name' => 'FRIES','description' => 'Crisp, golden fries.','image' => 'uploads/menu/3/nWy6gMOCX5I78wcEeesYbm0UaXJZI1qQA8H9pEfT.jpeg','category_id' => 11,'price' => 3.54]);
        Menu::create(['restaurant_id' => '3','name' => 'POUTINE','description' => 'KFC\'s take on a Canadian classic. Crisp golden fries, cheese curds and gravy.','image' => 'uploads/menu/3/UGi35EcO6SBxcJ95LveFuCpSGyzTWKlz6BE7kk3p.jpeg','category_id' => 11,'price' => 5.64]);
        Menu::create(['restaurant_id' => '3','name' => 'HOMESTYLE COLESLAW','description' => 'Homestyle coleslaw with our sweet vinaigrette.','image' => 'uploads/menu/3/OtGm4fc5Y3LIqBWtyIuE2DzvPesXCQYroUQuUu1q.jpeg','category_id' => 10,'price' => 3.54]);
        Menu::create(['restaurant_id' => '3','name' => 'STRAWERRY SWIRL CHEESECAKE','description' => 'Indulge in our creamy Strawberry Swirl cheesecake.','image' => 'uploads/menu/3/NqDmnf27Dr0TvANwIuSIHK1eF1vZk3AqCHXEVVeG.jpeg','category_id' => 5,'price' => 4.66]);
        Menu::create(['restaurant_id' => '3','name' => '25 PIECE PARTY PACK','description' => '25 pieces of our Canadian farm raised and hand-breaded Secret Recipe chicken, 2 large golden fries, large gravy and 3 large homestyle sides of your choice. A feast fit for the hungriest of friends and family.','image' => 'uploads/menu/3/25_Bucket_Feast.jpg','category_id' => 9,'price' => 38.99]);
        Menu::create(['restaurant_id' => '3','name' => 'SANDWICH BUCKET','description' => '2 Double Tender sandwiches and 2 choices of Big Crunch or Zinger sandwiches served with large fries.','image' => 'uploads/menu/3/sandwich_bucket_newfmi.jpg','category_id' => 19,'price' => 26.99]);
        Menu::create(['restaurant_id' => '3','name' => 'GO BUCKET - KENTUCKY FLATBREAD','description' => 'Our flatbread filled with 1 white meat chicken tender hand-breaded in our 11 herds and spices, topped with lettuce and pepper mayo. Served with individual fries. Good to go!','image' => 'uploads/menu/3/GB_K_FlatBread.jpg','category_id' => 29,'price' => 3.49]);
        Menu::create(['restaurant_id' => '3','name' => 'SMALL POPCORN CHICKEN','description' => 'Bite-sized chicken. Big on flavour.','image' => 'uploads/menu/3/s_pop_chk.jpg','category_id' => 29,'price' => 5.99]);

        Menu::create(['restaurant_id' => '4','name' => 'Inspiration','description' => 'Spring mix, cucumbers, sun-dried cherry tomatoes, Kalamata olives, Balsamic vinaigrette','image' => '','category_id' => 10,'price' => 12.00]);
        Menu::create(['restaurant_id' => '4','name' => 'Greek','description' => 'imported Dodoni Greek feta, cucumbers, red onions, cherry tomatoes, olive tapenade, Greek oregano, olive oil','image' => '','category_id' => 10,'price' => 14.50]);
        Menu::create(['restaurant_id' => '4','name' => 'Margherita','description' => 'Fior di latte, basil','image' => '','category_id' => 14,'price' => 16.00]);
        Menu::create(['restaurant_id' => '4','name' => 'Californian','description' => 'arugula, sun-dried tomatoes, goat cheese, mozzarella','image' => '','category_id' => 14,'price' => 18.50]);
        Menu::create(['restaurant_id' => '4','name' => 'Homemade lasagna','description' => 'meat sauce, cream, mozzarella','image' => '','category_id' => 17,'price' => 20.50]);
        Menu::create(['restaurant_id' => '4','name' => 'Linguine with seafood','description' => 'tomato sauce, shrimp, scallops, clams, mussels, shallots','image' => '','category_id' => 17,'price' => 26.00]);
        Menu::create(['restaurant_id' => '4','name' => 'Baklava cheesecake','description' => 'Creamy cheesecake filled and topped with chunks of baklava.','image' => '','category_id' => 5,'price' => 8.00]);
        Menu::create(['restaurant_id' => '4','name' => 'Sicilian','description' => 'Italian sausage, capers, Kalamata olives, red onions, hot peppers, Fior di latte.','image' => '','category_id' => 14,'price' => 20.00]);
        Menu::create(['restaurant_id' => '4','name' => 'Penne Da Vinci','description' => 'Cream, white wine, goat cheese, shallots, arugula, cherry tomatoes.','image' => '','category_id' => 17,'price' => 22.50]);
        Menu::create(['restaurant_id' => '4','name' => 'Chicken Parmigiana','description' => 'Chicken breast, Panko bread crumbs, parmesan, traditional tomato sauce, mozzarella, linguine napoletana.','image' => '','category_id' => 9,'price' => 26.50]);

        Menu::create(['restaurant_id' => '5','name' => 'Beyond Meatball','description' => 'Our Beyond Meatball sub is a saucy classic featuring the tasty plant-based Beyond Meatball.','image' => 'uploads/menu/5/64f8yKnQHj0YLCT0klezcyof8nDAT0rgzV4hVF5h.jpeg','category_id' => 19,'price' => 6.45]);
        Menu::create(['restaurant_id' => '5','name' => 'Cold Cut Combo','description' => 'Delicious deli meats, topped with crisp vegetables','image' => 'uploads/menu/5/TvIOo8nos7tEU4VD9hDARScN1bulrvL1OqC6kxtm.jpeg','category_id' => 19,'price' => 5.99]);
        Menu::create(['restaurant_id' => '5','name' => 'Pizza Sub Melt','description' => 'The Italian sandwich par excellence','image' => 'uploads/menu/5/lLiOPrQP0cysvc8H89RLQ0HtVN4rzGzfGODI4nod.jpeg','category_id' => 19,'price' => 5.97]);
        Menu::create(['restaurant_id' => '5','name' => 'Tuna','description' => 'Made with flaked tuna, mixed with mayo','image' => 'uploads/menu/5/QqQ79SBzkRrZaZ9vhJiJlXw4kdOQ87MKKJd7tFMp.jpeg','category_id' => 19,'price' => 6.54]);
        Menu::create(['restaurant_id' => '5','name' => 'Cookies','description' => 'Tender and moist, it is the perfect way to complement your meal.','image' => 'uploads/menu/5/hX1g4yuf7VbJJ5K6yLMuU1c6jYj8faFOMLIawBr0.jpeg','category_id' => 5,'price' => 2.05]);
        Menu::create(['restaurant_id' => '5','name' => 'Brisk Lemon Iced Tea','description' => 'This is the Brisk® that started it all. The original iced tea with tons of attitude. The one with the bold lemon flavour that kicked iced tea off the back porch. Now that’s Brisk, baby!','image' => 'uploads/menu/5/Subway_BriskLemonIcedTea_234x140_72_RGB.jpg','category_id' => 30,'price' => 1.89]);
        Menu::create(['restaurant_id' => '5','name' => 'Egg and Bacon English Muffin','description' => 'Our Egg and Bacon English Muffin Sandwich will leave you wanting seconds. English muffin filled with tasty bacon, egg and processed white cheddar then toasted just the way you like it.','image' => 'uploads/menu/5/Subway_EnglishMuffinBaconEgg_234x140_72_RGB.jpg','category_id' => 4,'price' => 3.49]);
        Menu::create(['restaurant_id' => '5','name' => 'Black Forest Ham','description' => 'Everything but the bread! Turn any one of your favourite sandwiches into a salad. Add crunch to your meal with lettuce, red onions, tomatoes, cucumbers and much more!','image' => 'uploads/menu/5/Subway_SaladBlackForestHam_234x140_72_RGB.jpg','category_id' => 10,'price' => 7.49]);
        Menu::create(['restaurant_id' => '5','name' => 'Chicken & Bacon Ranch','description' => 'Everything but the bread! Turn any one of your favourite sandwiches into a salad. Add crunch to your meal with lettuce, red onions, tomatoes, cucumbers and much more!','image' => 'uploads/menu/5/Subway_SaladChickenBaconRanch_594x334_72_RGB.jpg','category_id' => 10,'price' => 9.69]);
        Menu::create(['restaurant_id' => '5','name' => 'Tuna Salad','description' => 'Everything but the bread! Turn any one of your favourite sandwiches into a salad. Add crunch to your meal with lettuce, red onions, tomatoes, cucumbers and much more!','image' => 'uploads/menu/5/Subway_SaladTuna_594x334_72_RGB.jpg','category_id' => 10,'price' => 6.89]);

        Menu::create(['restaurant_id' => '6','name' => 'Fried Chicken Dumplings','description' => 'Crispy chicken dumplings served with sweet chili sauce','image' => 'uploads/menu/6/frieddumplings.jpg','category_id' => 29,'price' => 4.00]);
        Menu::create(['restaurant_id' => '6','name' => 'Steamed Chicken Dumplings','description' => 'Chicken wrapped in savoury dough, served with peanut sauce and green onion.','image' => 'uploads/menu/6/appetizers-chickendumplings.jpg','category_id' => 29,'price' => 4.00]);
        Menu::create(['restaurant_id' => '6','name' => 'Spring Roll','description' => 'Lettuce, bean sprouts, carrot, coriander, mint, vermicelli and shrimp wrapped in rice paper and served with peanut sauce','image' => 'uploads/menu/6/appetizers-springroll.jpg','category_id' => 29,'price' => 3.75]);
        Menu::create(['restaurant_id' => '6','name' => 'Imperial Roll','description' => 'Crispy roll filled with vegetables. Enjoy with your choice of Thai Express plum sauce or FS sauce','image' => 'uploads/menu/6/appetizers-imperialroll.jpg','category_id' => 29,'price' => 1.70]);
        Menu::create(['restaurant_id' => '6','name' => 'Mango Salad','description' => 'Mango, lettuce, coriander, shallots, red pepper and mint served with Thai dressing','image' => 'uploads/menu/6/appetizers-mangosalad.jpg','category_id' => 10,'price' => 4.50]);
        Menu::create(['restaurant_id' => '6','name' => 'Thai Soup','description' => 'A fragrant Thai chicken broth filled with rice noodles, bean sprouts, onion, carrot, green onion, coriander, topped with crispy fried red shallot with your choice of Shrimp, Beef, Chicken, Vegetables, Tofu or Fish.','image' => 'uploads/menu/6/soups-thai.jpg','category_id' => 6,'price' => 8.98]);
        Menu::create(['restaurant_id' => '6','name' => 'General Curry','description' => 'Crisp pieces of battered fried chicken with one of the three delicious curries (Red, Green or Yellow) served on steamed rice.','image' => 'uploads/menu/6/curry-general.jpg','category_id' => 31,'price' => 9.88]);
        Menu::create(['restaurant_id' => '6','name' => 'Thai Fried Rice','description' => 'A Thai classic; Fried rice with egg, green onion, carrot, onion, with your choice of Shrimp, Beef, Chicken, Vegetables, Tofu, Fish or Vegan (contains no seafood or animal product). With Pineapple and tomato','image' => 'uploads/menu/6/FriedRice_ThaiFriedRice.jpg','category_id' => 31,'price' => 8.98]);
        Menu::create(['restaurant_id' => '6','name' => 'Pad Thai','description' => 'Thin rice noodles stir-fried with our sweet and sour sauce, egg, bean sprouts, green onion, tofu and salted radish with your choice of Shrimp, Beef, Chicken, Vegetables, Tofu, Fish or Vegan (contains no seafood or animal product).','image' => 'uploads/menu/6/Noodles_PadThai.jpg','category_id' => 32,'price' => 8.98]);
        Menu::create(['restaurant_id' => '6','name' => 'Pad See Ew','description' => 'Broad rice noodles served with our house brand soy sauce, egg and Chinese broccoli with your choice of Shrimp, Beef, Chicken, Vegetables, Tofu, Fish or Vegan* (contains no seafood or animal product).','image' => 'uploads/menu/6/Noodles_PadSeeEw.jpg','category_id' => 32,'price' => 8.98]);

        Menu::create(['restaurant_id' => '7','name' => 'SMARTIES SHAKE','description' => 'For a limited time, indulge in our creamy hand spun Smarties Shake. Velvety Vanilla Soft Serve, Smarties pieces and vanilla sauce are blended to perfection and finished with a sweet whipped topping just for you.','image' => 'uploads/menu/7/02990-32 BK_Web_SmartiesShake_500x540_CR_0.png','category_id' => 5,'price' => 3.49]);
        Menu::create(['restaurant_id' => '7','name' => 'APPLE TURNOVER','description' => 'Our Apple Turnover has a flaky golden crust with a delicious warm apple filling. It\'s the perfect way to finish any meal.','image' => 'uploads/menu/7/Hero-Apple Turnover.png','category_id' => 5,'price' => 3.29]);
        Menu::create(['restaurant_id' => '7','name' => 'JALAPENO CHEESY BITES','description' => 'Wrapped in a crispy coating, packed with jalapeno pieces, and bursting with cheesy goodness. The Jalapeno Cheesy Bites are the perfect snack that will leave you craving more. Get \'em while you can, limited time only.','image' => 'uploads/menu/7/209-41-BKCA_Web_JalapenoCheesyBites_500x540-CR_1.png','category_id' => 29,'price' => 4.99]);
        Menu::create(['restaurant_id' => '7','name' => 'CHICKEN NUGGETS','description' => 'Made with white meat, our bite-sized Chicken Nuggets are tender and juicy on the inside and crispy on the outside. Coated in a homestyle seasoned breading, they are perfect for dipping in any of our delicious dipping sauces.','image' => 'uploads/menu/7/02936-74 BK_Chicken_Nuggets_500x540_CR.png','category_id' => 29,'price' => 5.99]);
        Menu::create(['restaurant_id' => '7','name' => 'FRENCH FRIES','description' => 'More delicious than ever, our signature piping hot, thick cut French Fries are golden on the outside and fluffy on the inside.','image' => 'uploads/menu/7/HERO_0001_French_Fries.png','category_id' => 11,'price' => 2.99]);
        Menu::create(['restaurant_id' => '7','name' => 'POUTINE','description' => 'Try delicious poutine at BURGER KING and enjoy the classic taste of fresh golden fries smothered with cheese curds & piping hot gravy. The flavours melt together to create a truly Canadian favourite.','image' => 'uploads/menu/7/04409-31 DIG Silo Poutine 500x540_CR.png','category_id' => 11,'price' => 6.99]);
        Menu::create(['restaurant_id' => '7','name' => 'SAUSAGE, EGG & CHEESE CROISSAN\'WICH','description' => 'Our grab-and-go Sausage, Egg & Cheese CROISSAN’WICH is piled high with savoury sizzling sausage, eggs, and melted cheese on a toasted, flaky croissant.','image' => 'uploads/menu/7/Detail_Croissanwich_Sausage_egg_cheese.png','category_id' => 4,'price' => 5.99]);
        Menu::create(['restaurant_id' => '7','name' => 'PANCAKES','description' => 'Three warm, fluffy pancakes flavoured with a hint of vanilla and served with syrup.','image' => 'uploads/menu/7/Hero-Pancakes-2_0.png','category_id' => 4,'price' => 4.99]);
        Menu::create(['restaurant_id' => '7','name' => 'ROADHOUSE KING','description' => 'The Roadhouse KING™ Sandwich features two 1/4 lb savory flame-grilled beef patties, topped with 4 half-strips of thick-cut smoked bacon, our signature crispy onion rings, tangy BBQ sauce, American cheese and creamy mayonnaise all on our sesame seed bun.','image' => 'uploads/menu/7/Roadhouse-King-Silo-500x540_CR.png','category_id' => 20,'price' => 9.99]);
        Menu::create(['restaurant_id' => '7','name' => 'BACON & CHEESE WHOPPER','description' => 'A ¼ lb of savory flame-grilled beef topped with thick-cut smoked bacon, melted cheese, ripe tomatoes, fresh lettuce, creamy mayonnaise, ketchup, crunchy pickles, and sliced onions, all on a warm, toasted, sesame seed bun.','image' => 'uploads/menu/7/03299-87 DIG_Silo_Bacon Cheese Whopper_500x540_CR.png','category_id' => 20,'price' => 8.99]);

        Menu::create(['restaurant_id' => '8','name' => 'SHAKES','description' => 'Chocolate, Strawberry or Vanilla made with real ice cream.','image' => 'uploads/menu/8/shakes.jpg','category_id' => 5,'price' => 4.49]);
        Menu::create(['restaurant_id' => '8','name' => 'BEVERAGES','description' => 'Refreshing selections include Coca-Cola, Diet Coke, 7UP, Dr. Pepper, Root Beer, Lemonade, Minute Maid Light Lemonade, Iced Tea, Milk, Coffee and Hot Cocoa.','image' => 'uploads/menu/8/cups.jpg','category_id' => 30,'price' => 2.19]);
        Menu::create(['restaurant_id' => '8','name' => 'FRENCH FRIES','description' => 'Fresh, hand-cut potatoes prepared in 100% sunflower oil.','image' => 'uploads/menu/8/fries.jpg','category_id' => 11,'price' => 3.89]);
        Menu::create(['restaurant_id' => '8','name' => 'HAMBURGER','description' => 'Toasted buns, beef patty, onions, lettuce, sauce spread unchanged since 1948 and tomatoes.','image' => 'uploads/menu/8/hamburger.jpg','category_id' => 20,'price' => 5.39]);
        Menu::create(['restaurant_id' => '8','name' => 'CHEESEBURGER','description' => 'Toasted buns, sliced cheese, beef patty, onions, lettuce, sauce spread unchanged since 1948 and tomatoes.','image' => 'uploads/menu/8/cheeseburger.jpg','category_id' => 20,'price' => 6.29]);
        Menu::create(['restaurant_id' => '8','name' => 'DOUBLE-DOUBLE','description' => 'Toasted buns, 2 cheese slices, 2 beef patties, onions, lettuce, sauce spread unchanged since 1948 and tomatoes.','image' => 'uploads/menu/8/double-double.jpg','category_id' => 20,'price' => 7.49]);
        Menu::create(['restaurant_id' => '8','name' => 'HAMBURGER MEAL','description' => 'Toasted buns, beef patty, onions, lettuce, sauce spread unchanged since 1948 and tomatoes. Served with fried and a beverage.','image' => 'uploads/menu/8/hamburger-meal.jpg','category_id' => 20,'price' => 9.89]);
        Menu::create(['restaurant_id' => '8','name' => 'CHEESEBURGER MEAL','description' => 'Toasted buns, sliced cheese, beef patty, onions, lettuce, sauce spread unchanged since 1948 and tomatoes. Served with fries and a beverage.','image' => 'uploads/menu/8/cheeseburger-meal.jpg','category_id' => 20,'price' => 10.49]);
        Menu::create(['restaurant_id' => '8','name' => 'DOUBLE-DOUBLE MEAL','description' => 'Toasted buns, 2 cheese slices, 2 beef patties, onions, lettuce, sauce spread unchanged since 1948 and tomatoes. Served with fries and a beverage.','image' => 'uploads/menu/8/double-double-meal.jpg','category_id' => 20,'price' => 11.79]);
        Menu::create(['restaurant_id' => '8','name' => 'ANIMAL STYLE FRIES','description' => 'Fresh, hand-cut potatoes prepared in 100% sunflower oil. Served topped with our sauce spread unchanged since 1948.','image' => 'uploads/menu/8/maxresdefault.jpg','category_id' => 11,'price' => 7.29]);

        Menu::create(['restaurant_id' => '9','name' => 'Shrimp Tempura','description' => 'Shrimp tempura, soy sauce, potato, daikon radish, sesame oil. (1pc)','image' => 'uploads/menu/9/29_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 0.69]);
        Menu::create(['restaurant_id' => '9','name' => 'Takoyaki','description' => 'Minced or diced octopus, tempura scraps, pickled ginger and green onion. (1pc)','image' => 'uploads/menu/9/07_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 0.69]);
        Menu::create(['restaurant_id' => '9','name' => 'Yakitori','description' => 'Grilled chicken on skewers with savory-sweet sauce. (1pc)','image' => 'uploads/menu/9/03_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 1.29]);
        Menu::create(['restaurant_id' => '9','name' => 'Tempura Platter','description' => 'Zucchini tempura, pumpkin tempura, sweet potato tempura, eggplant tempura, soy sauce, potato, daikon radish, sesame oil. (8pcs)','image' => 'uploads/menu/9/05_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 8.99]);
        Menu::create(['restaurant_id' => '9','name' => 'Sashimi Platter','description' => 'Salmon, mackerel, squid, oil fish, flying fish caviar, imitation crab, sweet tofu, octopus. (8pcs)','image' => 'uploads/menu/9/01_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 8.99]);
        Menu::create(['restaurant_id' => '9','name' => 'California Maki Roll','description' => 'Sushi rice, crab meat, avocado, fish roe, cucumber, toasted sesame. (4pcs)','image' => 'uploads/menu/9/panthermedia_15526657_1748x1167-1.jpg','category_id' => 15,'price' => 6.99]);
        Menu::create(['restaurant_id' => '9','name' => 'Green Dragon Roll','description' => 'Sushi rice, avocado topped, deep fried shrimp, crab meat, cucumber and tobiko. (4pcs)','image' => 'uploads/menu/9/22.jpg','category_id' => 15,'price' => 7.99]);
        Menu::create(['restaurant_id' => '9','name' => 'Kamikaze Salmon Roll','description' => 'Sushi rice, spicy salmon, crab stick, cucumber, masago, nori. (4pcs)','image' => 'uploads/menu/9/09_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 6.99]);
        Menu::create(['restaurant_id' => '9','name' => 'Phoenix Maki Roll','description' => 'Sushi rice, salmon, yellowtail, shrimp, avocado, spicy mayo, tempura flakes, tuna and tobiko. (4pcs)','image' => 'uploads/menu/9/11_fisshu_400-2018-08-09.jpg','category_id' => 15,'price' => 7.99]);
        Menu::create(['restaurant_id' => '9','name' => 'Ice cream','description' => 'Choose from green tea, chocolate, mango and vanilla.','image' => 'uploads/menu/9/download.jpg','category_id' => 15,'price' => 1.99]);

        Menu::create(['restaurant_id' => '10','name' => 'Cheese Cake','description' => 'Strawberry cheese cake','image' => 'uploads/menu/10/menu-images_500x281-cheese-cake_en.jpg','category_id' => 5,'price' => 2.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Smoked Meat Egg Roll','description' => 'Served with plum or honey mustard sauce.','image' => 'uploads/menu/10/home_1950x750-smoked-meat-eggrolls-2_en.jpg','category_id' => 29,'price' => 10.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Smoked Meat Sandwich','description' => 'Our small sandwich served on rye bread with homemade fries, coleslaw and dill.','image' => 'uploads/menu/10/home_1950x750-smoked-meat-sandwich-3_en.jpg','category_id' => 19,'price' => 16.50]);
        Menu::create(['restaurant_id' => '10','name' => 'Carbonera Pasta','description' => '35% cream, butter, egg yolk, topped with smoked meat and shallots.','image' => 'uploads/menu/10/home_1950x750-spaghetti-carbonara_en.jpg','category_id' => 17,'price' => 17.50]);
        Menu::create(['restaurant_id' => '10','name' => 'Hot Dog Poutine','description' => 'Made with our famous gravy, grilled all beef hot dogs','image' => 'uploads/menu/10/home_dunns-banner-poutine_en.jpg','category_id' => 11,'price' => 13.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Chocolate Chocolate Chocolate Cake','description' => 'Chocolate cake with chocolate frosting and chocolate cream.','image' => 'uploads/menu/10/menu_1950x750-chocolate-cake_en.jpg','category_id' => 5,'price' => 7.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Carrot Caramel Cheescake','description' => 'Cheese cake with caramel frosting and carrot and caramel bits','image' => 'uploads/menu/10/menu-images_500x281-carrot-cake_en.jpg','category_id' => 5,'price' => 7.00]);
        Menu::create(['restaurant_id' => '10','name' => 'French Onion Soup','description' => 'Homemade onion soup, croutons and topped with melted mozzarella cheese.','image' => 'uploads/menu/10/menu_1950x750-french-onion-soup_en.jpg','category_id' => 6,'price' => 8.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Cheese Pizza','description' => 'Tomato sauce and mozarella cheese','image' => 'uploads/menu/10/menu_1950x750-cheese-pizza_en.jpg','category_id' => 14,'price' => 11.00]);
        Menu::create(['restaurant_id' => '10','name' => 'Buffalo Ranch Chicken Salad','description' => 'Crispy chicken tenders tossed in buffalo sauce, mixed greens, shredded carrots, red cabbage, red onion, cucumbers, cherry tomatoes, avocado, garlic pepper rach dressing','image' => 'uploads/menu/10/menu_1950x750-battered-chicken-in-salad_en.jpg','category_id' => 21,'price' => 17.50]);

        Menu::create(['restaurant_id' => '11','name' => 'Scores Combo','description' => '2 miniburgers (topped with bacon, cheese and chipotle sauce), 4 bites of tender General Tao chicken breast fillets and 4 cheese sticks. Served with Scores marinara sauce.','image' => 'uploads/menu/11/COMBO_SCORES.png','category_id' => 29,'price' => 14.25]);
        Menu::create(['restaurant_id' => '11','name' => 'Classic Combo','description' => '2 chicken wings, 2 cheese sticks, 2 breaded tender chicken breast fillets and onion rings. Served with 3 sauces: spicy wing, marinara and honey-Dijon.','image' => 'uploads/menu/11/COMBO_CLASSIQUE.png','category_id' => 29,'price' => 19.00]);
        Menu::create(['restaurant_id' => '11','name' => 'Hand Tossed Garlic Parmesan Fries','description' => 'Dive into our hand tossed fries with garlic and parmesan.','image' => 'uploads/menu/11/frites_ail_et_parmesan.png','category_id' => 11,'price' => 4.95]);
        Menu::create(['restaurant_id' => '11','name' => 'Kapow! Shrimp','description' => 'Delicious popcorn shrimp with jalapenos served with our house chipotle pepper sauce. A flavour explosion in your mouth!','image' => 'uploads/menu/11/CREVETTES_KAPOW.png','category_id' => 29,'price' => 10.50]);
        Menu::create(['restaurant_id' => '11','name' => 'Cheese Sticks','description' => 'Served with our marinara sauce.','image' => 'uploads/menu/11/BATONNETS_DE_FROMAGE.png','category_id' => 29,'price' => 5.50]);
        Menu::create(['restaurant_id' => '11','name' => 'The Grand Saladier','description' => 'Discover a range of fresh ingredients and possibilities to create your own salad or savor hot soups at will.','image' => 'uploads/menu/11/le_grand_saladier.png','category_id' => 10,'price' => 6.95]);
        Menu::create(['restaurant_id' => '11','name' => 'Traditional Brochette','description' => 'Delicious marinated and grilled chicken breast pieces. Served on your choice of Scores rice or basmati rice.','image' => 'uploads/menu/11/BROCHETTE_DE_POULET_TRADITIONNELLE.png','category_id' => 21,'price' => 13.45]);
        Menu::create(['restaurant_id' => '11','name' => 'Chicken Ceasar Wrap','description' => 'Marinated and grilled chicken strips served with bacon, romain lettuce, parmesan and Caesar salad dressing.','image' => 'uploads/menu/11/wrap_cesar_au_poulet_avec_bacon.png','category_id' => 19,'price' => 11.95]);
        Menu::create(['restaurant_id' => '11','name' => 'Scores Grilled Cheese Gourmet','description' => 'No one can resist this reinvented grilled cheese sandwich made with roasted chicken leg, Swiss cheese and spinach spread.','image' => 'uploads/menu/11/grilled-cheese-2018.png','category_id' => 19,'price' => 14.75]);
        Menu::create(['restaurant_id' => '11','name' => 'Ribs Poutine','description' => 'Crispy French fries, poutine sauce, cheese curds, 4 baby back ribs with Scores ribs sauce.','image' => 'uploads/menu/11/poutine_cotes_levees.png','category_id' => 11,'price' => 14.75]);

        Menu::create(['restaurant_id' => '12','name' => 'Western Sub','description' => 'Philly steak, mozzarella, onions mushrooms, tomatoes and lettuce.','image' => 'uploads/menu/12/WEB20_16_SUBMARINES_700x498_Western.jpg','category_id' => 19,'price' => 13.69]);
        Menu::create(['restaurant_id' => '12','name' => 'Chicken and Broccoli Pennine','description' => 'Served with Alfredo sauce, broccoli, chicken breast strips, white wine and garlic.','image' => 'uploads/menu/12/76870-700.png','category_id' => 17,'price' => 16.99]);
        Menu::create(['restaurant_id' => '12','name' => 'Caesar Salad','description' => 'Crisp romaine lettuce with croutons and bacon bits, topped with a creamy garlic dressing.','image' => 'uploads/menu/12/77234-700.png','category_id' => 10,'price' => 11.49]);
        Menu::create(['restaurant_id' => '12','name' => 'Choco Mikes','description' => 'Deliciously rich and moist chocolate cake, covered with scrumptious chocolate ganache, for the great classics lovers.','image' => 'uploads/menu/12/76851-700.png','category_id' => 5,'price' => 4.99]);
        Menu::create(['restaurant_id' => '12','name' => 'Homemade Waffle-cut Chips','description' => 'Seasoned with Cajun spices.','image' => 'uploads/menu/12/77240-700.png','category_id' => 29,'price' => 4.49]);
        Menu::create(['restaurant_id' => '12','name' => 'Mix Mikes','description' => '4 cheese sticks, popcorn shrimp, 4 bruschetta rolls, and waffle-cut chips seasoned with Cajun spices. Two dips of your choice.','image' => 'uploads/menu/12/76833-700.png','category_id' => 29,'price' => 15.99]);
        Menu::create(['restaurant_id' => '12','name' => 'Neapolitan Pizza','description' => 'Tomato sauce and pizza mozzarella cheese.','image' => 'uploads/menu/12/WEB19_35_new_website_pizzas_400x320_8_Napolitaine.png','category_id' => 14,'price' => 12.99]);
        Menu::create(['restaurant_id' => '12','name' => 'BBQ Chicken Pizza','description' => 'Barbecue sauce, strips of chicken breast, three-cheese bland, mushrooms and bacon.','image' => 'uploads/menu/12/WEB19_35_new_website_pizzas_400x320_1_Poulet-BBQ.png','category_id' => 14,'price' => 15.49]);
        Menu::create(['restaurant_id' => '12','name' => 'Field of Dreams Pizza','description' => 'Tomato sauce, three-cheese blend, quartered artichoke hearts, broccoli, mushrooms, onions, red peppers, basil pesto, green and black olives and sun-dried tomatoes.','image' => 'uploads/menu/12/WEB19_35_new_website_pizzas_400x320_4_Jardin-de-Reves.png','category_id' => 14,'price' => 14.29]);
        Menu::create(['restaurant_id' => '12','name' => 'Carnivore Pizza','description' => 'Pepperoni, Philly steak, capicollo, ham, bacon, Bolognese sauce and pizza mozzarella cheese.','image' => 'uploads/menu/12/WEB19_35_new_website_pizzas_400x320_5_Carnivore.png','category_id' => 14,'price' => 16.79]);

        Menu::create(['restaurant_id' => '13','name' => 'Chicken Noodle Soup','description' => 'Pieces of roasted chicken, noodles and fresh vegetables in a soupe.','image' => 'uploads/menu/13/10003@2x.jpg','category_id' => 6,'price' => 4.25]);
        Menu::create(['restaurant_id' => '13','name' => 'Cream of Chicken Soup','description' => 'Rotisserie chicken pieces served in a velvety cream.','image' => 'uploads/menu/13/10001@2x.jpg','category_id' => 6,'price' => 4.25]);
        Menu::create(['restaurant_id' => '13','name' => 'Nun\'s Pastries','description' => 'Two soft, yet crispy nun\'s pastries, topped with St-Donat sugar cream sauce','image' => 'uploads/menu/13/11494@2x.jpg','category_id' => 5,'price' => 4.95]);
        Menu::create(['restaurant_id' => '13','name' => '8 Cheese Sticks','description' => 'Crispy chesse sticks served with marinara sauce.','image' => 'uploads/menu/13/10109@2x.jpg','category_id' => 29,'price' => 10.25]);
        Menu::create(['restaurant_id' => '13','name' => '24 Chicken Wings','description' => 'St-Hubert chicken wings served with 3 dipping sauces of your choice.','image' => 'uploads/menu/13/10111@2x.jpg','category_id' => 29,'price' => 21.75]);
        Menu::create(['restaurant_id' => '13','name' => 'Maple Delight','description' => 'A generous piece of cake layered with maple mousse and served with 100% pure maple syrup from Quebec.','image' => 'uploads/menu/13/10061@2x.jpg','category_id' => 5,'price' => 5.25]);
        Menu::create(['restaurant_id' => '13','name' => 'Half Rack of Pork Ribs','description' => 'Our pork ribs are larger, tender and meatier than ever! For a limited time, they are served with 4 free chicken wings.','image' => 'uploads/menu/13/10027@2x.jpg','category_id' => 21,'price' => 18.50]);
        Menu::create(['restaurant_id' => '13','name' => 'Rotisserie Chicken Leg','description' => 'Our St-Hubert chicken, spit-roasted for three hours.','image' => 'uploads/menu/13/10013@2x.jpg','category_id' => 9,'price' => 13.50]);
        Menu::create(['restaurant_id' => '13','name' => 'Double Chicken Leg','description' => 'Our St-Hubert chicken is spit-roasted for three hours.','image' => 'uploads/menu/13/10015@2x.jpg','category_id' => 9,'price' => 16.50]);
        Menu::create(['restaurant_id' => '13','name' => 'Original St-Burger','description' => 'St-Hubert\'s signature burger! Crispy chicken breast, creamy coleslaw, chopped lettuce, pickles, and a roasted red pepper spread, served in a poppy seed bun.','image' => 'uploads/menu/13/11331@2x.jpg','category_id' => 20,'price' => 15.00]);

        Menu::create(['restaurant_id' => '14','name' => 'Kibeh','description' => 'Lebanese Beef Croquettes.','image' => 'uploads/menu/14/FS-Al-Boustan0543-1024x683.png','category_id' => 29,'price' => 4.25]);
        Menu::create(['restaurant_id' => '14','name' => 'Garlic Potatoes','description' => 'Golden seasoned garlic potatoes served with garlic sauce.','image' => 'uploads/menu/14/FS-Al-Boustan0556-1024x683.png','category_id' => 29,'price' => 2.95]);
        Menu::create(['restaurant_id' => '14','name' => 'Falafel','description' => 'Fried balls, chickpea and spice.','image' => 'uploads/menu/14/FS-Al-Boustan0519-1024x683.png','category_id' => 29,'price' => 3.65]);
        Menu::create(['restaurant_id' => '14','name' => 'Tabouleh','description' => 'Parsley and Bulgur salad with diced tomatoes, onions, and citrus dressing.','image' => 'uploads/menu/14/FS-Al-Boustan0486-1024x683.png','category_id' => 10,'price' => 4.50]);
        Menu::create(['restaurant_id' => '14','name' => 'Baklava','description' => 'Pastry made of layers of filo with chopped nuts held together with honey','image' => 'uploads/menu/14/BAKLAVA-1-1024x683.png','category_id' => 5,'price' => 2.25]);
        Menu::create(['restaurant_id' => '14','name' => 'Chicken Shawarma','description' => 'Marinated chicken. Served with rice, potatoes, coleslaw, and sauce.','image' => 'uploads/menu/14/FS-Al-Boustan0630-1024x683.png','category_id' => 22,'price' => 12.50]);
        Menu::create(['restaurant_id' => '14','name' => 'Beef Shawarma','description' => 'Marinated beef. Served with rice potatoes, coleslaw, and sauces.','image' => 'uploads/menu/14/FS-Al-Boustan0671-1024x683.png','category_id' => 22,'price' => 12.50]);
        Menu::create(['restaurant_id' => '14','name' => 'Shawarma Combo','description' => 'Beef and chicken shawarma. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/14/FS-Al-Boustan0639-1024x683.png','category_id' => 22,'price' => 12.75]);
        Menu::create(['restaurant_id' => '14','name' => 'Brochette Chicken, Beef or Mixed','description' => 'Two sticks of tender chicken or beef cubes or one of each. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/14/FS-Al-Boustan0681-1-1024x683.png','category_id' => 22,'price' => 13.95]);
        Menu::create(['restaurant_id' => '14','name' => 'Vegetarian Platter','description' => 'Mousakha Sauce, one Falafel, Eggplant, Oriental Omelette, Coleslaw, Garlic Potatoes, Tabouleh, Rice (or lentil), and sauces.','image' => 'uploads/menu/14/FS-Al-Boustan0699-1-1024x683.png','category_id' => 13,'price' =>9.95]);

        Menu::create(['restaurant_id' => '15','name' => 'Dave\'s Double','description' => 'A half-pound* of hot n’ juicy beef, cheese, crisp lettuce, tomato, pickle, ketchup, mayo, and onion on a toasted bun. More meat means more to love.','image' => 'uploads/menu/15/219_medium_CA_en.jpg','category_id' => 20,'price' => 7.29]);
        Menu::create(['restaurant_id' => '15','name' => 'Baconator','description' => 'A half-pound* of hot n’ juicy beef, melted cheese, 6 slices of crispy Applewood smoked bacon, ketchup, and mayo. Carnivores rejoice!','image' => 'uploads/menu/15/221_medium_CA_en.jpg','category_id' => 20,'price' => 7.29]);
        Menu::create(['restaurant_id' => '15','name' => 'Bacon Deluxe 3/4lb.* Triple','description' => 'Three — that’s right, THREE — hot n’ juicy beef patties with 3 strips of Applewood smoked bacon, melted cheese, crisp lettuce, tomato, pickle, ketchup, mayo, and onion on a toasted bun. Hunger doesn’t stand a chance.','image' => 'uploads/menu/15/456_medium_CA_en.jpg','category_id' => 20,'price' => 9.99]);
        Menu::create(['restaurant_id' => '15','name' => 'Spicy Chicken Sandwich','description' => 'A juicy, 100% Canadian chicken breast marinated and breaded in our unique, fiery blend of peppers and spices to deliver more flavour inside and out — cooled down with crisp lettuce, tomato, and mayo.','image' => 'uploads/menu/15/231_medium_CA_en.jpg','category_id' => 20,'price' => 5.79]);
        Menu::create(['restaurant_id' => '15','name' => 'Grilled Asiago Ranch Chicken Club','description' => 'A sizzling, 100% Canadian chicken breast grilled to perfection, with thick Applewood smoked bacon, Asiago cheese, creamy ranch sauce, crisp lettuce, and tomato, all on a toasted bun.','image' => 'uploads/menu/15/236_medium_CA_en.jpg','category_id' => 20,'price' => 6.19]);
        Menu::create(['restaurant_id' => '15','name' => 'Southwest Avocado','description' => 'Herb-marinated, grilled 100% Canadian chicken breast hot off the grill, pepper jack cheese, diced tomatoes, cool, creamy avocado, topped with Applewood smoked bacon and Renée’s Gourmet® Southwest Ranch Dressing, all on lettuce blend.','image' => 'uploads/menu/15/469_medium_CA_en.jpg','category_id' => 10,'price' => 7.29]);
        Menu::create(['restaurant_id' => '15','name' => 'Taco Salad','description' => 'Our famous hearty chili, crisp lettuce, shredded cheese, diced tomatoes, salsa, sour cream, and tortilla chips.','image' => 'uploads/menu/15/241_medium_CA_en.jpg','category_id' => 10,'price' => 8.59]);
        Menu::create(['restaurant_id' => '15','name' => 'Fries','description' => 'Skin-on, sea-salted fries served hot and crispy. The world loves them for a reason.','image' => 'uploads/menu/15/245_medium_CA_en.jpg','category_id' => 11,'price' => 1.89]);
        Menu::create(['restaurant_id' => '15','name' => 'Chili Cheese Fries','description' => 'Our skin-on, sea-salted fries topped with our hearty chili, shredded cheese, and rich, creamy cheese sauce. Easy to love. Hard to beat.','image' => 'uploads/menu/15/248_medium_CA_en.jpg','category_id' => 11,'price' => 4.29]);
        Menu::create(['restaurant_id' => '15','name' => 'Bacon Cheddar Cheese Sauce Baked Potato','description' => 'A hot, fluffy potato topped with rich, creamy cheese sauce and crisp bacon bits.  Because nothing goes with a potato like cheese and bacon.','image' => 'uploads/menu/15/259_medium_CA_en.jpg','category_id' => 11,'price' => 2.99]);

        Menu::create(['restaurant_id' => '16','name' => 'Butter Chicken','description' => 'Boneless chicken breast, tomato sauce, tandoori masala, heavy cream, garam masala, mince onion and minced garlic.','image' => 'uploads/menu/16/Butter-Chicken-IMAGE-64.jpg','category_id' => 9,'price' => 16.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Lamb Karahi','description' => 'The lamb is cooked along with onions, tomatoes, ginger-garlic any spices.','image' => 'uploads/menu/16/Kadai-Gosht.jpg','category_id' => 27,'price' => 17.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Qeema Bhuna','description' => 'Minced mutton meat, ginger, cinnamon, tomatoes, lime juice, green chillies. butter.','image' => 'uploads/menu/16/Bhuna-Keema-2-2.jpg','category_id' => 27,'price' => 14.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Tandoori Chicken Legs','description' => 'Whole chicken legs, garam masala, mango chutney, curry spice, lemon juice.','image' => 'uploads/menu/16/chicken-tandori-1526595014.jpg','category_id' => 9,'price' => 11.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Fish Masala','description' => 'Catfish, tomato paste, garam masala, ginger, avocado oil, curry leaves, fresh coconut.','image' => 'uploads/menu/16/20131020-161453.jpg','category_id' => 27,'price' => 15.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Okra Bhindi Masala','description' => 'Bhindi, lady finger, garam masala, kasuri methi, tomatoes, chili, tomato paste, okra and ginger.','image' => 'uploads/menu/16/bhindi-masala-recipe-11.jpg','category_id' => 13,'price' => 12.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Dall Makhani','description' => 'Red kidney beans, urad dal, cream, garam masala, chili, brown basmati, beluga lentils, butter.','image' => 'uploads/menu/16/dal-makhani-1.jpg','category_id' => 13,'price' => 12.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Chana Masala','description' => 'Coconut oil, fresh green chilies, chickpeas, garam masala, tomato, lemon juice.','image' => 'uploads/menu/16/Indian-Chana-Masala-2.jpg','category_id' => 13,'price' => 12.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Naan Bread','description' => 'Baked with olive oil, anise seeds and garlic.','image' => 'uploads/menu/16/naan-recipe-2.jpg','category_id' => 27,'price' => 1.95]);
        Menu::create(['restaurant_id' => '16','name' => 'Kheer','description' => 'Basmati rice, kaju, saffron, golden raisins, sliced almonds, rose water, sugar.','image' => 'uploads/menu/16/sabudana-kheer-recipe.jpg','category_id' => 5,'price' => 3.95]);

        Menu::create(['restaurant_id' => '17','name' => 'Chocolate Lava Crunch Cake','description' => 'Oven baked chocolate cakes, crunchy on the outside with molten chocolate on the inside.','image' => 'uploads/menu/17/F_LAVA.jpg','category_id' => 5,'price' => 4.25]);
        Menu::create(['restaurant_id' => '17','name' => 'Marbled Cookie Brownie','description' => 'Satisfy your sweet tooth! Taste the decadent blend of gooey milk chocolate chunk cookie and delicious fudge brownie. Oven-baked to perfection and cut into 6 pieces','image' => 'uploads/menu/17/F_MRBRWNE.jpg','category_id' => 5,'price' => 4.25]);
        Menu::create(['restaurant_id' => '17','name' => 'Coke','description' => 'The authentic cola sensation that is a refreshing part of sharing life\'s enjoyable moments','image' => 'uploads/menu/17/F_COKE.jpg','category_id' => 30,'price' => 2.99]);
        Menu::create(['restaurant_id' => '17','name' => 'Spicy Jalapeno - Pineapple','description' => 'Tender bites of lightly breaded, 100% whole breast white meat chicken, topped with sweet and spicy mango-habanero sauce, a blend of cheese made with mozzarella and cheddar, jalapeno and pineapple.','image' => 'uploads/menu/17/S_SCSJP.jpg','category_id' => 9,'price' => 8.50]);
        Menu::create(['restaurant_id' => '17','name' => 'Wings','description' => 'Our chicken wings are now tastier than ever. Sauced with your choice of Hot, Honey Garlic, BBQ, or Mango Habanero.','image' => 'uploads/menu/17/S_BONEIN.jpg','category_id' => 9,'price' => 12.25]);
        Menu::create(['restaurant_id' => '17','name' => 'Domino\'s Pizza Cheesy Bread','description' => 'A blend of cheddar and mozzarella cheeses baked to perfection. With marinara sauce.','image' => 'uploads/menu/17/F_CHEBRD.jpg','category_id' => 29,'price' => 9.25]);
        Menu::create(['restaurant_id' => '17','name' => 'Parmesan Bites','description' => 'Oven-baked bread bites handmade from buttery-tasting dough and seasoned with garlic and Parmesan. Add marinara or your favourite Dipping cup for an additional charge.','image' => 'uploads/menu/17/F_PARM.jpg','category_id' => 29,'price' => 6.25]);
        Menu::create(['restaurant_id' => '17','name' => 'Veggie Pizza','description' => 'A medley of fresh green peppers, onion, tomatoes, mushrooms, and olives.','image' => 'uploads/menu/17/S_PIZVX.jpg','category_id' => 14,'price' => 11.99]);
        Menu::create(['restaurant_id' => '17','name' => 'Brooklyn Pizza','description' => 'Specifically engineered to be big, thin, and perfectly foldable.','image' => 'uploads/menu/17/S_BRKLYN.jpg','category_id' => 14,'price' => 13.99]);
        Menu::create(['restaurant_id' => '17','name' => 'Chicken Bacon Ranch Pizza','description' => 'A Ranch Sauce base with a Mozzarella/Cheddar Cheese blend, fresh tomatoes, green peppers, all white-meat chicken and bacon.','image' => 'uploads/menu/17/S_PIZCBR.jpg','category_id' => 14,'price' => 15.99]);

        Menu::create(['restaurant_id' => '18','name' => 'Baklava','description' => 'Pastry made of layers of filo with chopped nuts held together with honey','image' => 'uploads/menu/18/10ca19da6350.jpg','category_id' => 5,'price' => 1.99]);
        Menu::create(['restaurant_id' => '18','name' => 'Garlic Potatoes','description' => 'Golden seasoned garlic potatoes served with garlic sauce.','image' => 'uploads/menu/18/4c8ad24b3cf1.jpg','category_id' => 29,'price' => 7.99]);
        Menu::create(['restaurant_id' => '18','name' => 'Merguez Plate','description' => 'Lamb and beef sausage. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/18/eacac5d7e30d.jpg','category_id' => 22,'price' => 11.50]);
        Menu::create(['restaurant_id' => '18','name' => 'Kafta Plate','description' => 'Beef meatballs. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/18/946c1eae02db.jpg','category_id' => 22,'price' => 11.50]);
        Menu::create(['restaurant_id' => '18','name' => 'Shawarma Plate','description' => 'Beef and chicken shawarma. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/18/2be815f67077.jpg','category_id' => 22,'price' => 11.99]);
        Menu::create(['restaurant_id' => '18','name' => 'Vegetarian Plate','description' => 'Spinach, baba ganoush, fattoush, lettuce.','image' => 'uploads/menu/18/74b717211da3.jpg','category_id' => 22,'price' => 10.75]);
        Menu::create(['restaurant_id' => '18','name' => 'Hummus Plate','description' => 'Tahini, sumac, olive oil, lemon juice, garlic, sea salt.','image' => 'uploads/menu/18/85f63b63d3ae.jpg','category_id' => 22,'price' => 6.99]);
        Menu::create(['restaurant_id' => '18','name' => 'Shish Taouk Plate','description' => 'Two sticks of tender chicken or beef cubes or one of each. Served with rice, potatoes, coleslaw, and sauces.','image' => 'uploads/menu/18/89e4e7d998ba.jpg','category_id' => 22,'price' => 11.75]);
        Menu::create(['restaurant_id' => '18','name' => 'Chef\'s Salad','description' => 'Salad dressing with olive oil, lemon juice, garlic, sumac, pomegranate molasses, lettuce and tomatoes.','image' => 'uploads/menu/18/b5499efa8201.jpg','category_id' => 10,'price' => 4.99]);
        Menu::create(['restaurant_id' => '18','name' => 'Grilled Veggies','description' => 'Mousakha Sauce, one Falafel, Eggplant, Oriental Omelette, Coleslaw, Garlic Potatoes, Tabouleh, Rice (or lentil), and sauces.','image' => 'uploads/menu/18/f78ddc5975bc.jpg','category_id' => 13,'price' => 8.99]);

        Menu::create(['restaurant_id' => '19','name' => 'Carnitas','description' => 'Pulled pork with pico de gallo. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/Slow-Cooker-Pork-Carnitas-Recipe-8.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Tingas','description' => 'Pulled chicken cooked with onions and chipotle tomato sauce and sour cream. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/chicken-tinga-tacos-small-6.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Chorizo','description' => 'Ground pork with spicy potatoes and cheese. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/mexican-chorizo-recipes-2342791-9-5b0daa3c30371300370f196f.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Cochinita','description' => 'Marinated pork yucatan style with marinated red onions. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/Instant-Pot-Cochinita-Pibil-Recipe-1-1.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Beef','description' => 'Grilled beef with onions and coriander. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/ground-beef-tacos-01.jpg','category_id' => 26,'price' => 45.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Mushrooms','description' => 'Sauted mushrooms with mild peppers and pico de gallo. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/mushroom-tacos-reshoot-3-small-6.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Nopales','description' => 'Sauted cactus with pico de gallo. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/IMG_0538-2.jpg','category_id' => 26,'price' => 40.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Pastor','description' => 'Marinated pork grilled with pineapple and served with onions and coriandre.  Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/download.jpg','category_id' => 26,'price' => 45.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Fish','description' => 'Baja style tilapia with pico de gallo and chipotle mayo. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/Easy-Fish-Tacos-22.jpg','category_id' => 26,'price' => 45.00]);
        Menu::create(['restaurant_id' => '19','name' => 'Cecina','description' => 'Oaxaca style specialty beef with pico de gallo. Served with 15 tortillas de mais, salsa verde, salsa roja and lime.','image' => 'uploads/menu/19/9-TacosCampechanosdeCarneLandscapeweb.jpg','category_id' => 26,'price' => 50.00]);

        Menu::create(['restaurant_id' => '20','name' => 'Grilled Hot Dog','description' => 'Grilled wiener dog on bun. All dressed is served with mustard, chopped onions, fresh coleslaw.','image' => 'uploads/menu/20/cf5b33d7470de88073ac868091709a8b.jpg','category_id' => 20,'price' => 1.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Michigan Hot Dog','description' => 'Steamed wiener dog on bun. All dressed is served with meat chili sauce, diced onions and mustard.','image' => 'uploads/menu/20/item-89705953350a53a4cc40.jpg','category_id' => 20,'price' => 2.25]);
        Menu::create(['restaurant_id' => '20','name' => 'Fries','description' => 'A large amount of golden brown french fries.','image' => 'uploads/menu/20/288507207_0e9ed51863.jpg','category_id' => 11,'price' => 2.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Fries & Sauce','description' => 'Some of our golden brown frnech fries topped with gravy sauce.','image' => 'uploads/menu/20/o.jpg','category_id' => 11,'price' => 3.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Poutine','description' => 'Our famous poutine with golden brown french fries, authentic cheese curds and gravy sauce.','image' => 'uploads/menu/20/la-belle-province.jpg','category_id' => 11,'price' => 5.75]);
        Menu::create(['restaurant_id' => '20','name' => 'Italian Poutine','description' => 'Gravy covered frnech fries and cheese curds topped with ground beef, bell peppers and meat chili sauce.','image' => 'uploads/menu/20/poutine-italienne.jpg','category_id' => 11,'price' => 6.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Hamburger','description' => 'Grilled patty between two buns, with a choice of lettuce, tomato, onion, pickles and bacon.','image' => 'uploads/menu/20/pataterie-la-belle-province.jpg','category_id' => 20,'price' => 4.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Cheesebuger','description' => 'Grilled patty between two buns, with a choice of cheese, lettuce, tomato, onion, pickles and bacon.','image' => 'uploads/menu/20/la-belle-province (1).jpg','category_id' => 20,'price' => 5.49]);
        Menu::create(['restaurant_id' => '20','name' => 'Smoked Meat Sandwich','description' => 'Authentic Montreal smoked meat between two slices of bread with pickles, coleslaw and mustard.','image' => 'uploads/menu/20/download.jpg','category_id' => 19,'price' => 6.89]);
        Menu::create(['restaurant_id' => '20','name' => 'Sub','description' => 'Lettuce, tomato, cheese, onions and pickles inside a sub, with the choice of either steak, pepperoni, chicken or smoke meat.','image' => 'uploads/menu/20/sous-marin-la-belle-pro-300x300.jpg','category_id' => 19,'price' => 7.49]);

        Menu::create(['restaurant_id' => '21','name' => 'Grilled Hot Dogs','description' => 'Made with Lafleur\'s exclusive sausage. Worthy of summer\'s best grilled hot dogs.','image' => 'uploads/menu/21/hd_grille.e0ec9a04aff7.jpg','category_id' => 20,'price' => 4.99]);
        Menu::create(['restaurant_id' => '21','name' => 'Hamburger','description' => 'Our amazingly tasty special sauce! 100% beef patty without additives.','image' => 'uploads/menu/21/Lafleur-HamburgerLafleur-nocheese.704961681a93.jpg','category_id' => 20,'price' => 4.69]);
        Menu::create(['restaurant_id' => '21','name' => 'Original Hamburger','description' => 'The original-the best! 100% beef patty without additives.','image' => 'uploads/menu/21/Lafleur-HamburgerOriginal-nocheese.1ec099b46a3e.jpg','category_id' => 20,'price' => 3.99]);
        Menu::create(['restaurant_id' => '21','name' => 'Supreme Hot Dog','description' => 'Bacon slices and cheese. There\'s a reason it\'s called the "Supreme"!','image' => 'uploads/menu/21/Lafleur-HotdogSupreme.7524508e01ec.jpg','category_id' => 20,'price' => 5.69]);
        Menu::create(['restaurant_id' => '21','name' => 'Onion Rings','description' => 'Cooked in canola oil. Onion rings count as a vegetable, right?','image' => 'uploads/menu/21/Lafleur-OnionsRings.de9815010cac.jpg','category_id' => 20,'price' => 3.69]);
        Menu::create(['restaurant_id' => '21','name' => 'Pogo','description' => 'Both crispy and soft. That true Pogo taste.','image' => 'uploads/menu/21/Lafleur-Pogo.b31a36d74e5b.jpg','category_id' => 20,'price' => 2.99]);
        Menu::create(['restaurant_id' => '21','name' => 'Poutine','description' => 'Cheese curds from here. Our homemade sauce made from beef.','image' => 'uploads/menu/21/Lafleur-Poutine.cd5a98e27afb.jpg','category_id' => 11,'price' => 4.99]);
        Menu::create(['restaurant_id' => '21','name' => 'Italian Poutine','description' => 'Our homemade sauce since 1951. Fresh potatoes cooked in 100% canola oil.','image' => 'uploads/menu/21/Lafleur-Poutine-Italienne.463c1ab2a806.jpg','category_id' => 11,'price' => 6.69]);
        Menu::create(['restaurant_id' => '21','name' => 'Texan Chicken','description' => 'Fresh, crunchy veggies. Honey, mayonnaise, chipotle: the choice is yours!','image' => 'uploads/menu/21/','category_id' => 20,'price' => 6.99]);
        Menu::create(['restaurant_id' => '21','name' => 'Smoke Meat','description' => 'Fresh meat with a truly smoked taste! For that heavenly taste!','image' => 'uploads/menu/21/Lafleur-SmokeMeat.f2927d0dca9b.jpg','category_id' => 20,'price' => 5.99]);

        Menu::create(['restaurant_id' => '22','name' => 'Red Tuna Sashimi','description' => 'Raw, thinly sliced bluefin tuna. (3pcs)','image' => 'uploads/menu/22/454629837-58a4b2de5f9b58819cf851f5.jpg','category_id' => 15,'price' => 5.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Surf Clam Sashimi','description' => 'Raw surf clam. (3pcs)','image' => 'uploads/menu/22/960064bd9ce184c9623164ed8d05e0de.jpg','category_id' => 15,'price' => 4.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Pink Salmon','description' => 'Sushi rice and thinly sliced raw salmon. (2pcs)','image' => 'uploads/menu/22/unnamed.jpg','category_id' => 15,'price' => 4.49]);
        Menu::create(['restaurant_id' => '22','name' => 'Octopus','description' => 'Sushi rice, seaweed and octopus. (2pcs)','image' => 'uploads/menu/22/main-qimg-8ba1a075b233dca5b4732c5a59c08550.jpg','category_id' => 15,'price' => 3.49]);
        Menu::create(['restaurant_id' => '22','name' => 'Seaweed Salad','description' => 'Soy sauce, dried wakame seaweed, sesame oil, rice wine.','image' => 'uploads/menu/22/download.jpg','category_id' => 10,'price' => 5.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Miso Soup','description' => 'Miso paste, firm tofu, green onion, dried seaweed.','image' => 'uploads/menu/22/miso-soup-horizontal-jpg-1529350400.jpg','category_id' => 6,'price' => 1.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Chicken Skewer','description' => 'Skinless chicken thighs, soy sauce, brown sugar. (6pcs)','image' => 'uploads/menu/22/chicken-skewers.jpg','category_id' => 9,'price' => 7.49]);
        Menu::create(['restaurant_id' => '22','name' => 'Fried Sesame Ball','description' => 'Red bean paste, glutinous rice flour, white sesame seeds, brown sugar. (6pcs)','image' => 'uploads/menu/22/fried-sesame-balls-8.jpg','category_id' => 29,'price' => 6.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Shrimp Tempura','description' => 'Shrimp, soy sauce, sesame oil, baking powder, flour and corn starch. (5pcs)','image' => 'uploads/menu/22/5d533e8af2a2cc68c7df75e7e2992b97.jpg','category_id' => 29,'price' => 8.99]);
        Menu::create(['restaurant_id' => '22','name' => 'Salmon Head','description' => 'Cooked salmon head. (2pcs)','image' => 'uploads/menu/22/855ee44c2d8b0f63771db0cdc43248b5.jpg','category_id' => 15,'price' => 5.49]);

        Menu::create(['restaurant_id' => '23','name' => 'Pikilia','description' => 'Taramosalata, tzatziki sauce, tomato, cucumber, feta cheese, artichoke, olives, pickled vegetables.','image' => 'uploads/menu/23/2c2c6cca592139b3ee7aacde28e03bf9.jpg','category_id' => 29,'price' => 14.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Kopanisti','description' => 'Roasted red peppers, feta cheese, red pepper flakes, oilive oil, garlic and crostini.','image' => 'uploads/menu/23/kopanisti-tablefortwoblog-1.jpg','category_id' => 29,'price' => 5.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Spanakopita','description' => 'Chopped spinash, yellow onion, garlic, olive oil, egg, feta cheese, dill weed, dough.','image' => 'uploads/menu/23/190213-spanakopita-283-1551192256.jpg','category_id' => 29,'price' => 6.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Greek Salad','description' => 'Cucumber, bell pepper, cherry tomato, onion, feta cheese, calamata olives and vinaigrette.','image' => 'uploads/menu/23/greek-salad-2-1200.jpg','category_id' => 10,'price' => 13.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Souvlaki Pita','description' => 'Chicken thighs, tzatziki sauce, olive oil, cucumber, romaine lettuce, cherry tomato, pita.','image' => 'uploads/menu/23/Pita - Copy.jpg','category_id' => 8,'price' => 6.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Souvlaki Stick','description' => 'Chicken thighs, garlic and spices.','image' => 'uploads/menu/23/Greek-Chicken-Souvlaki-Recipe-2.jpg','category_id' => 8,'price' => 5.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Vegetarian Pita','description' => 'Zucchini, red peppers, portobello mushroom, onion, olive oil, lettuce, feta cheese, pita.','image' => 'uploads/menu/23/Roasted-Vegetable-Pita-Sandwich-3.jpg','category_id' => 8,'price' => 6.00]);
        Menu::create(['restaurant_id' => '23','name' => 'Galaktoboureko','description' => 'Honey, lemon, cinnamon, sugar, milk, vanilla extract, semonila, butter and phyllo dough sheets.','image' => 'uploads/menu/23/recipe_main_Galaktoboureko_2.jpg','category_id' => 5,'price' => 4.50]);
        Menu::create(['restaurant_id' => '23','name' => 'Baklava','description' => 'Phyllo dough, chopped nuts, butter, cinnamon, sugar, vanilla extract, honey.','image' => 'uploads/menu/23/baklava-recipe-9.jpg','category_id' => 5,'price' => 4.50]);
        Menu::create(['restaurant_id' => '23','name' => 'Gyro Plate','description' => 'Rice pilaf, tzatziki sauce, pita, gyro meat, greek salad.','image' => 'uploads/menu/23/download.jpg','category_id' => 8,'price' => 15.00]);

        Menu::create(['restaurant_id' => '24','name' => 'General Tao Chicken','description' => 'General tao chicken on rice. Served with 2 imperial rolls or 1 egg roll.','image' => 'uploads/menu/24/download.jpg','category_id' => 25,'price' => 12.25]);
        Menu::create(['restaurant_id' => '24','name' => 'Sweet and Sour Chicken','description' => 'Sweet and sour chicken on rice. Served with 2 imperial rolls or 1 egg roll.','image' => 'uploads/menu/24/Sweet-Sour-Chicken-5-500x500.jpg','category_id' => 9,'price' => 12.25]);
        Menu::create(['restaurant_id' => '24','name' => 'Vegetable Fried Rice','description' => 'Peas, corn, carrots, bell peppers and rice. Served with 2 imperial rolls or 1 egg roll.','image' => 'uploads/menu/24/veggie-fried-rice-6.jpg','category_id' => 31,'price' => 8.25]);
        Menu::create(['restaurant_id' => '24','name' => 'Hong Kong Style Noodles','description' => 'Chicken, bell peppers, onions, egg noodles and green beans. Served with 2 imperial rolls or 1 egg roll.','image' => 'uploads/menu/24/hong-kong-crispy-noodle-650px.jpg','category_id' => 32,'price' => 11.45]);
        Menu::create(['restaurant_id' => '24','name' => 'Broccoli Beef','description' => 'Seasoned Beef, beef broth, white sesame seeds and steamed broccoli.','image' => 'uploads/menu/24/instant-pot-beef-and-broccoli-1-5.jpg','category_id' => 25,'price' => 5.25]);
        Menu::create(['restaurant_id' => '24','name' => 'Pineapple Chicken','description' => 'Chicken and pineapple. Served with fried rice and 3 imperial rolls.','image' => 'uploads/menu/24/pineapple-chicken-2.jpg','category_id' => 25,'price' => 10.00]);
        Menu::create(['restaurant_id' => '24','name' => '28 Pcs Sushi Combo','description' => '10 futomaki rolls, 8 maki rolls, 6 hsomaki rolls, 4 nigiri. All sushi may contain nuts or sesame seeds.','image' => 'uploads/menu/24/SBPT04_makiroll-650x650.jpg','category_id' => 15,'price' => 26.95]);
        Menu::create(['restaurant_id' => '24','name' => 'Salmon Poke Bol','description' => 'Cucumber, avocado, tamago, tempura, tobiko, carrots, mixed lettuce and salmon.','image' => 'uploads/menu/24/Recipe-Salmon-Poke-Bowl.jpg','category_id' => 15,'price' => 13.95]);
        Menu::create(['restaurant_id' => '24','name' => 'Smoked Salmon Sesame Salad','description' => 'Japanese vinaigrette, smoked salmon, creme cheese, mixed lettuce, tamago eggs, pollock, cucumber.','image' => 'uploads/menu/24/download (1).jpg','category_id' => 10,'price' => 12.95]);
        Menu::create(['restaurant_id' => '24','name' => 'Shrimp Won Ton Soup','description' => 'Minced pork, soy sauce, sesame oil, egg white, ginger, wontons.','image' => 'uploads/menu/24/Shrimp-Wonton-Soup-with-Kale2-720x720.jpg','category_id' => 6,'price' => 6.50]);

        Menu::create(['restaurant_id' => '25','name' => 'Cheese Naan','description' => 'Punjab region bread with cheese.','image' => 'uploads/menu/25/180_ab3863c904db3fc28005b036670f7da0.jpg','category_id' => 27,'price' => 4.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Onion Bhaji','description' => 'Deep-fried buttered onions.','image' => 'uploads/menu/25/180_c1753283e4fd612b866e5cc7f1f7f315.jpg','category_id' => 27,'price' => 4.50]);
        Menu::create(['restaurant_id' => '25','name' => 'Samosa','description' => 'Deep-fried triangle pastry filled with vegetables.','image' => 'uploads/menu/25/180_d38307a7ad0843a5489c4d60b4cdfe01.jpg','category_id' => 27,'price' => 3.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Steamed Rice','description' => 'Long grain white basmati rice.','image' => 'uploads/menu/25/180_e9b9d9141158a7fd5461d66be109b0ca.jpg','category_id' => 27,'price' => 4.25]);
        Menu::create(['restaurant_id' => '25','name' => 'Butter Chicken','description' => 'Chicken prepared with mild spices, almonds and nuts in a creamy sauce.','image' => 'uploads/menu/25/180_4768f98603c6c0638a207f1fc6840e29.jpg','category_id' => 9,'price' => 15.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Chicken Tikka','description' => 'Tender and juicy pieces of chicken grilled on skewers in the tandoor.','image' => 'uploads/menu/25/300_4c1691502bfeeedc696fa58b030534a6.jpg','category_id' => 9,'price' => 16.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Tarka Daal','description' => 'Pureed lentils with onions and spices.','image' => 'uploads/menu/25/300_4fb48602c43cecf507ebbcb06147bfe8.jpg','category_id' => 6,'price' => 9.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Achar Chutney','description' => 'Mango chutney or mixed pickles.','image' => 'uploads/menu/25/300_6ff333a4b9919bcf70768ae7e0478aa1.jpg','category_id' => 13,'price' => 1.95]);
        Menu::create(['restaurant_id' => '25','name' => 'King Prawn Bhuna','description' => 'Jumbo tiger shrimp cooked with fresh garlic, green peppers and tomatoes.','image' => 'uploads/menu/25/300_f9e717cc97ab40b7b195a958bc61b73a.jpg','category_id' => 27,'price' => 15.95]);
        Menu::create(['restaurant_id' => '25','name' => 'Seekh Kebab','description' => 'Ground beef marinated with oriental herbs and spices.','image' => 'uploads/menu/25/300_551e1c90ec034473a52fbf4748941161.jpg','category_id' => 27,'price' => 7.95]);

        Menu::create(['restaurant_id' => '26','name' => 'Arugula Salad','description' => 'Arugula salad, candied lemon vinaigrette, parmesan shavings, and cherry tomatoes.','image' => 'uploads/menu/26/Lemon-Arugula-Salad-with-Pine-Nuts-Image-6.jpg','category_id' => 10,'price' => 5.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Focaccia','description' => 'Oval pizza dough, herb oil, caramelized onions, and parmesan cheese.','image' => 'uploads/menu/26/Focaccia-Bread-SQUARE.jpg','category_id' => 7,'price' => 7.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Arancini','description' => '6 Balls of cheese risotto, breaded and fried with tomato sauce.','image' => 'uploads/menu/26/k_archive_4bd4b5bdd293c8fdebed5f39d865f38fe8e86df4.jpg','category_id' => 7,'price' => 14.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Polpette','description' => '6 Veal balls served in a tomato sauce with parmesan shavings.','image' => 'uploads/menu/26/polpette-fritte-18-083.jpg','category_id' => 7,'price' => 18.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Apero plater','description' => 'An assortment of cold cuts and cheese served with focaccia.','image' => 'uploads/menu/26/2647ffa1fd4ad769a03c5b326d2b421d.jpg','category_id' => 7,'price' => 16.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Vitello Tonnato','description' => 'Thin slices of veal tenderloin, tuna sauce, parmesan cheese and arugula.','image' => 'uploads/menu/26/vitello-tonnato-arrosto-830x625.jpg','category_id' => 7,'price' => 11.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Spicy Soppressata Pizza','description' => 'Tomato sauce, fior di latte, and spicy soppressata','image' => 'uploads/menu/26/20150702-spicy-salami-chile-honey-pizza-1-750x563.jpg','category_id' => 14,'price' => 15.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Prosciutto','description' => 'Tomato sauce, mozzarella, arugula, lemon ricotta, and prosciutto.','image' => 'uploads/menu/26/07f26b8773e0ceb0595836346d87ac50e867759b.jpg','category_id' => 14,'price' => 17.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Carciofi','description' => 'Tomato sauce, fior di latte, goat cheese, artichoke, black olive, and red onion.','image' => 'uploads/menu/26/180245b0-b38b-4cac-82a2-7e2ed9d8aa62.jpg','category_id' => 7,'price' => 15.00]);
        Menu::create(['restaurant_id' => '26','name' => 'Porchetta','description' => 'Bechamel Dijonnaise, fontina, porchetta, arugula, fried shallot, and mustard. Pizza on white base.','image' => 'uploads/menu/26/porchetta.jpg','category_id' => 14,'price' => 16.00]);

        Menu::create(['restaurant_id' => '27','name' => 'Classic Poutine','description' => 'A regular poutine with golden brown fries, cheese curds and homemade gravy.','image' => 'uploads/menu/27/la banquise-1001.jpg','category_id' => 11,'price' => 12.95]);
        Menu::create(['restaurant_id' => '27','name' => 'Matty Poutine','description' => 'A poutine topped with bacon, peppers, mushrooms and onions.','image' => 'uploads/menu/27/la banquise-1002.jpg','category_id' => 11,'price' => 15.95]);
        Menu::create(['restaurant_id' => '27','name' => 'Reggae Poutine','description' => 'A poutine topped with ground steak, guacamole, tomatoes and hot peppers.','image' => 'uploads/menu/27/la banquise-1003.jpg','category_id' => 11,'price' => 18.60]);
        Menu::create(['restaurant_id' => '27','name' => 'Chicks Poutine','description' => 'A poutine topped with breaded chicken.','image' => 'uploads/menu/27/la banquise-1004.jpg','category_id' => 11,'price' => 15.95]);
        Menu::create(['restaurant_id' => '27','name' => 'Triple Meat Poutine','description' => 'A poutine topped with ground steak, pepperoni and bacon.','image' => 'uploads/menu/27/la banquise-1005.jpg','category_id' => 11,'price' => 16.60]);
        Menu::create(['restaurant_id' => '27','name' => 'Rachel Poutine','description' => 'A poutine topped with onions, mushrooms and peppers.','image' => 'uploads/menu/27/la banquise-1006.jpg','category_id' => 11,'price' => 14.95]);
        Menu::create(['restaurant_id' => '27','name' => 'Vegan Poutine','description' => 'A poutine topped with vegan cheese and vegan gravy.','image' => 'uploads/menu/27/la banquise-1007.jpg','category_id' => 13,'price' => 15.95]);
        Menu::create(['restaurant_id' => '27','name' => 'Boogalou Poutine','description' => 'A poutine topped with pulled pork, creamy coleslaw and sour cream.','image' => 'uploads/menu/27/la banquise-1008.jpg','category_id' => 11,'price' => 19.65]);
        Menu::create(['restaurant_id' => '27','name' => 'South West Poutine','description' => 'A poutine topped with bacon, red onions, guacamole, onion rings and chipotle sauce.','image' => 'uploads/menu/27/la banquise-1009.jpg','category_id' => 11,'price' => 18.60]);
        Menu::create(['restaurant_id' => '27','name' => 'BOM Poutine','description' => 'A poutine topped with bacon, onions and merguez sausage.','image' => 'uploads/menu/27/la banquise-1015.jpg','category_id' => 11,'price' => 16.60]);

        Menu::create(['restaurant_id' => '28','name' => 'Popeye Green Juice','description' => 'Pineapple, apple, spinach, celery and lemon juice.','image' => 'uploads/menu/28/1257015f489e3a50d577b7f6c89c0f65.jpg','category_id' => 30,'price' => 7.50]);
        Menu::create(['restaurant_id' => '28','name' => 'Chapati Bread','description' => 'Indian flat bread hand rolled and served with vegan butter.','image' => 'uploads/menu/28/chapatis.jpg','category_id' => 13,'price' => 5.00]);
        Menu::create(['restaurant_id' => '28','name' => 'Chana Paratha','description' => 'Flat indian bread covered in cari made of chickpeas and potatoes, sour cream and mint and tamarin chutney.','image' => 'uploads/menu/28/chole_paratha-final.jpg','category_id' => 13,'price' => 7.50]);
        Menu::create(['restaurant_id' => '28','name' => 'Pakoras','description' => 'Bitesize spicy chickpea based fries served with mint and tamarin chutney.','image' => 'uploads/menu/28/Vegetable-Pakoras-4.jpg','category_id' => 13,'price' => 6.50]);
        Menu::create(['restaurant_id' => '28','name' => 'Bombay Banana Smoothie','description' => 'Banana, cocoa and soya milk, ginger, masala and dates.','image' => 'uploads/menu/28/Bombay-Banana-Smoothie-6.jpg','category_id' => 30,'price' => 6.75]);
        Menu::create(['restaurant_id' => '28','name' => 'Mango Lassi Smoothie','description' => 'Mango, cocoa milk, apple juice, banana and spinach.','image' => 'uploads/menu/28/Indian-Mango-Lassi-Recipe-500x500.jpg','category_id' => 30,'price' => 6.75]);
        Menu::create(['restaurant_id' => '28','name' => 'Dragon Salad Bowl','description' => 'Grated carrot, red cabbage & beetroot, daikon, lettuce, sprouts, seaweed, grilled sesame seeds, dragon sauce & grilled tofu.','image' => 'uploads/menu/28/dragon+bowl.jpg','category_id' => 10,'price' => 13.25]);
        Menu::create(['restaurant_id' => '28','name' => 'Thai Salad Bowl','description' => 'Steamed bok choy, marinated carrot & daikon, lettuce, grated carrot, peanuts, coriander, Thai peanut sauce & grilled tofu.','image' => 'uploads/menu/28/thai-bowl.jpg','category_id' => 10,'price' => 13.50]);
        Menu::create(['restaurant_id' => '28','name' => 'Tempeh Burger Wrap','description' => 'Grilled organic Noble Bean Tempeh served on whole wheat bread with caramelized onions, tomato, lettuce, pickle & chipotle mayo.','image' => 'uploads/menu/28/tempeh+bbq+wrap.jpg','category_id' => 13,'price' => 14.75]);
        Menu::create(['restaurant_id' => '28','name' => 'Veggie Burger Wrap','description' => 'Hearty garden pancake served on whole wheat bread with caramelized onions, tomato, lettuce, pickle & chipotle mayo.','image' => 'uploads/menu/28/vegepate+wrap.jpg','category_id' => 13,'price' => 14.75]);

        Menu::create(['restaurant_id' => '29','name' => 'Sweet Potato Pudding','description' => 'Made from sweet potatoes, raisins and rum.','image' => 'uploads/menu/29/15__299-2019-11-06.jpg','category_id' => 5,'price' => 8.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Accras','description' => 'Fried malanga, cassava flour, spicy mayo.','image' => 'uploads/menu/29/07__299-2019-11-06.jpg','category_id' => 28,'price' => 6.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Plantain Burger','description' => 'Beef, lettuce, tomatoes, pikliz, spicy mayo, cheese and our garlic plantains.','image' => 'uploads/menu/29/09__299-2019-11-06.jpg','category_id' => 28,'price' => 14.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Griot','description' => 'Fried and marinated pork cubes. Served with rice.','image' => 'uploads/menu/29/03__299-2019-11-06.jpg','category_id' => 28,'price' => 15.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Spicy BBQ Chicken','description' => 'Grilled chicken thigh with creole spices.','image' => 'uploads/menu/29/04__299-2019-11-06.jpg','category_id' => 28,'price' => 14.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Pate Kode','description' => 'Fried dough stuffed with smoked herring.','image' => 'uploads/menu/29/08__299-2019-11-06.jpg','category_id' => 28,'price' => 6.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Puff Pastry','description' => 'Made with choice of chicken or beef.','image' => 'uploads/menu/29/16__299-2019-11-06.jpg','category_id' => 28,'price' => 4.75]);
        Menu::create(['restaurant_id' => '29','name' => 'Tassot Cabrit','description' => 'Spiced and marinated lamb meat. Served with fried plantain and salad.','image' => 'uploads/menu/29/17__299-2019-11-06.jpg','category_id' => 28,'price' => 23.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Crispy Fish','description' => 'Breaded and fried redfish, served on white rice, with beans and salad.','image' => 'uploads/menu/29/19__299-2019-11-06.jpg','category_id' => 28,'price' => 24.00]);
        Menu::create(['restaurant_id' => '29','name' => 'Chicken Wings','description' => 'Chicken wings caramelized with Barbancourt rum.','image' => 'uploads/menu/29/25__299-2019-11-06.jpg','category_id' => 28,'price' => 9.00]);

        Menu::create(['restaurant_id' => '30','name' => '','description' => '','image' => 'uploads/menu/30/','category_id' => 21,'price' => 4.25]);

        Menu::create(['restaurant_id' => '31','name' => '','description' => '','image' => 'uploads/menu/31/','category_id' => 10,'price' => 4.25]);

        Menu::create(['restaurant_id' => '32','name' => '','description' => '','image' => 'uploads/menu/32/','category_id' => 5,'price' => 4.25]);

        Menu::create(['restaurant_id' => '33','name' => '','description' => '','image' => 'uploads/menu/33/','category_id' => 4,'price' => 4.25]);

        Menu::create(['restaurant_id' => '34','name' => '','description' => '','image' => 'uploads/menu/34/','category_id' => 12,'price' => 4.25]);

        Menu::create(['restaurant_id' => '35','name' => '','description' => '','image' => 'uploads/menu/35/','category_id' => 19,'price' => 4.25]);

        Menu::create(['restaurant_id' => '36','name' => '','description' => '','image' => 'uploads/menu/36/','category_id' => 24,'price' => 4.25]);

        Menu::create(['restaurant_id' => '37','name' => '','description' => '','image' => 'uploads/menu/37/','category_id' => 5,'price' => 4.25]);

        Menu::create(['restaurant_id' => '38','name' => '','description' => '','image' => 'uploads/menu/38/','category_id' => 12,'price' => 4.25]);

        Menu::create(['restaurant_id' => '39','name' => '','description' => '','image' => 'uploads/menu/39/','category_id' => 30,'price' => 4.25]);

        Menu::create(['restaurant_id' => '40','name' => '','description' => '','image' => 'uploads/menu/40/','category_id' => 21,'price' => 4.25]);
    }
}
